comment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('update_comment/<int:postpk>/<int:commentpk>/',views.update_comment, name='update_comment'),
    path('delete_comment/<int:postpk>/<int:commentpk>/',views.delete_comment, name='delete_comment'),
]

myBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from post.views import post_list
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',post_list),
    path('/', include('post.urls')),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/',views.post_detail, name='post_detail'),
    path('create_post/',views.create_post, name='create'),
    path('update_post/<int:pk>/',views.update_post, name='update_post'),
    path('delete_post/<int:pk>/', views.delete_post, name='delete_post'),
    path('search/', views.search, name="search"),
    path('category/<slug:category_slug>/', views.category_view, name="category_view"),
]

comment/models.py
from django.db import models
from post.models import post
from account.models import user

# Create your models here.
class comment(models.Model):
    post=models.ForeignKey(post, on_delete=models.CASCADE, null=True)
    author=models.ForeignKey(user, on_delete=models.CASCADE, null=True)
    content=models.TextField(null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

comment/forms.py
from django import forms
from .models import comment

class PostComment(forms.ModelForm):
    class Meta:
        model=comment
        fields = [
            'post',
            'author',
            'content',
        ]

comment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import comment
from post.models import post
from .forms import PostComment

# Create your views here.
def update_comment(request, postpk, commentpk):
    curComment=get_object_or_404(comment,pk=commentpk)
    curPost=get_object_or_404(post, pk=postpk)
    if request.method=='POST':
        curComment.content=request.POST['content']
        curComment.save()
        return redirect('post_detail',pk=curPost.pk)
    return render(request,'comment/comment_update.html',{'curComment':curComment})

def delete_comment(request, postpk, commentpk):
    curPost=get_object_or_404(post,pk=postpk)
    delComment = get_object_or_404(comment, pk=commentpk)
    delComment.delete()
    return redirect('post_detail', pk=curPost.pk)

comment/templates/comment/comment_update.html
{% extends 'post/post_list.html' %}
{% block content %}
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<title>Edit Comment</title>
</head>
<body>
	<div class="container">
		<div class="m-5">
			<h1>댓글 수정</h1>
			<hr/>
			<form method='post' enctype="multipart/form-data">
				{% csrf_token %}
				<table>
					<tbody>
						<tr>
							<th><label for="id_content">댓글:</label></th>
							<td><textarea name="content" cols="40" rows="10" required="" id="id_content">{{ curComment.content}}</textarea></td>
						</tr>
						</tbody>
					</table>
					<button type="submit" class="btn btn-primary" style="margin-left: 370px;">수정</button>
			</form>
		</div>
	</div>
</body>
</html>
{% endblock %}